name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file /home/runner/work/atividade-somativa2-devops/atividade-somativa2-devops/Dockerfile --tag my-image-name:$(date +%s)




  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "testing"
      - name: Run Docker
      - uses: docker/login-action@v1
        with:
              registry: private-registry-url
              username: ${{ secrets.CI_REGISTRY_USER  }}
              password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - run: docker run -p 8080:8080 -d my-image-name:$(date +%s)
      - uses: AppThreat/sast-scan-action@master


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finito!"
